### PR TITLE
Hatice

### PR DESCRIPTION
**Pull request by hatkes**

### CODE REVIEW

**Comment by incitekman** [comment]
Good job

**Comment by hatkes** [comment]
done

**Comment by incitekman** [comment]
very good.thanks Hatice

**Review by incitekman — COMMENTED** [review]
Very good.Thank Hatice

**Comment by incitekman** [comment]
Good Job

**Comment by incitekman** [comment]
Good Job

**Review by incitekman — APPROVED** [review]
gGod Job! Hatice

**Pull request merged**
